# Sprint 3: NumPy & Statistics

## Epic 1: Basics of Statistics

https://lms.codeacademyberlin.com/content/data/Module-1/Project-1/Sprint-3 

Exercise 1 

Given, there are 5 numbers in the data set: (8, 12, 16, 24, 4).

What is the standard deviation?
* 6.88 (2dp)

And, what will be the sum of deviations of individual data points from their mean?
* 47.36

Exercise 2

If some outliers are introduced to the dataset, what will happen to the Standard Deviation? Will it increase, decrease or remain the same?
* Increase

Exercise 3 - no Numpy

Suppose the below positively skewed distribution has a median of 30, which of the following statement is true?

A) Mean is greater than 30
D) Mode is less than 30

* E) Both A and D


Exercise 4

Which value can be the possible value for the median of the below distribution?
* 27 ?

Assume the data are distributed as follows:

In [10]:
import numpy as np

random_arr = np.array([10, 10, 10, 10, 11, 11, 12, 13, 14, 15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35, 35, 35, 37, 37, 37, 37, 39, 39, 39,40, 40, 43, 43, 44, 44, 46, 46, 46, 47, 49, 52, 53, 54])

print(np.median(random_arr))

27.0


Exercise 5-6-7 (no Numpy)

Given the following distribution:
What is the shape of the distribution? 
* Positive skewed unimodal

What would you consider to be the most appropriate measure of the center for this data?
* Median, because it takes the skew into account

If Y axis represents the number of individuals and X axis – salary of the individual in thousands. How many individuals have salary less than 10 thousands? (no Numpy)
* 35

Exercise 8

We have a set of positive numbers. If a single value of the set is altered what must change?

A) Mean
B) Median
C) Mode
D) All of these

* It depends on the values:
  * Mean and median *always* change (assuming the value is not added or removed)
  * Mode may change depending on the set and alteration.

Hint: try to create a Numpy array and calculate mean median and mode, then alter it and see what changes

In [28]:
## this doesn't relate directly to the above because the array was expanded
single_value = 3000000
print(np.median(random_arr))
print(len(random_arr))

random_arr_plus_value = np.append(random_arr, single_value)  #concatenation
print(np.mean(random_arr_plus_value))
print(np.median(random_arr_plus_value))
print(len(random_arr_plus_value))

27.0
95
31277.59375
27.0
96


Exercise 9

The chart shows hourly consultancy rate of 10 people. Calculate the standard deviation of the salaries of the 10 employees. 

In [29]:
salaries = np.array([25,25,25,40,40,35,50,50,50,50])
print(np.std(salaries))

10.44030650891055


Exercise 10 (no Numpy)

Which of the following random variables is discrete?

* B) the number of pens purchased by a student in a year


Exercise 11 (no Numpy)

Which of the below normal distributions will have the greatest spread?

A) mu=5, sigma =1.5

B) mu=10, sigma =1.0

C) mu=5, sigma =1.65

D) mu=8, sigma =1.2

E) mu=10, sigma =1.6

* C

Because
* sigma =  SD.         larger SD -> most variation from mean

* mu =     mean.       smaller mu -> more affected by SD (larger proportion of data covered)

* co-efficient of variation (CV) is the ratio of SD to mean. higher CV indicates greater spread, proportionally

* C has the biggest variance and the smallest mean, as well as the highest CV (0.33)


## Other Exercises

### 100 numpy exercises
https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

#### 1. Import the numpy package under the name `np` (★☆☆)
#### 2. Print the numpy version and the configuration (★☆☆)

In [1]:
import numpy as np
print(np.__version__)

1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
### with zeros (not really null?)
null_vector_zero = np.zeros(10)

print("Zero vector:  ", null_vector_zero)
print(type(null_vector_zero))
print(type(null_vector_zero[0]))
print("Memory address: ", null_vector_zero.data)


Zero vector:   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
Memory address:  <memory at 0x7f34a8e4b700>


In [6]:
## With numpy empty (as 0 is not null in Python), yet it still displays as zeros (?) https://numpy.org/doc/stable/reference/generated/numpy.empty.html
## note: the dots indicate it is type 'float'
null_vector_empty = np.empty(10)

print("Empty vector: ",null_vector_empty)
print("Data structure: ",type(null_vector_empty))
print("Class of data inside (Numpy): ",null_vector_empty.dtype)
print("Class of data inside (Python): ",type(null_vector_empty[0]))
print("Memory address: ", null_vector_empty.data)
print("Elements: ", null_vector_empty.size)

Empty vector:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Data structure:  <class 'numpy.ndarray'>
Class of data inside (Numpy):  float64
Class of data inside (Python):  <class 'numpy.float64'>
Memory address:  <memory at 0x7f34a8e4bb80>
Elements:  10


In [17]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
x = null_vector_zero
y = null_vector_empty

# .size is the number of elements and .itemsize is bytes per item
print("Memory size of zero numpy array in bytes:",
      x.size * x.itemsize)
print("Memory size of empty numpy array in bytes:",
      y.size * y.itemsize)

Memory size of zero numpy array in bytes: 80
Memory size of empty numpy array in bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [8]:
np.put(null_vector_empty, 4, 1)
print(null_vector_empty)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
# notes: it's arange, not arrange. also upper limit is exclusive (50 not 49)
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
np.flip([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.array([[0,1,2],[3,4,5],[6,7,8]])
print(matrix_3)
#OR arange into a shape?
print(np.arange(9).reshape((3,3)))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
np.flatnonzero([1,2,0,0,4,0])

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


#### 12. Create a 3x3x3 array with random values (★☆☆)



In [16]:
np.random.rand(3,3,3)

array([[[0.14204151, 0.44366382, 0.290836  ],
        [0.69717116, 0.84661364, 0.3596445 ],
        [0.00320362, 0.81240942, 0.77447098]],

       [[0.33018582, 0.28591294, 0.44926314],
        [0.59324199, 0.81928999, 0.98669439],
        [0.50699348, 0.17529923, 0.58882977]],

       [[0.31748235, 0.20973522, 0.91671486],
        [0.6133947 , 0.85105783, 0.30284731],
        [0.07256837, 0.03391138, 0.14682008]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
ran_arr_10 = np.random.rand(10,10)
print(np.min(ran_arr_10))
print(np.max(ran_arr_10))

0.002887890915977964
0.9958443772435603


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [28]:
ran_vec_30 = np.random.rand(10)
np.mean(ran_vec_30)

0.5179757645188958


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
border_array = np.ones([3,3])
#print(border_array)
#print(np.put(border_array, [1,1], 0)) # put only works on vectors, and couldn't get .place to work
border_array[1][1] = 0                 # good old normal index- is that okay in numpy?
print(border_array)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [15]:
np.pad(border_array, 1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)